// src/components/admin/ActionsPolicyForm.tsx
import { useEffect, useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export interface ActionsPolicyDraft { allowedCommands: string; maxPatchBytes: number; permissionMode: string; }

export function ActionsPolicyForm({ allowedCommands, maxPatchBytes, permissionMode, onSave }: ActionsPolicyDraft & { onSave: (draft: ActionsPolicyDraft) => void | Promise<void> }) {
  const initial = useMemo(() => ({ allowedCommands, maxPatchBytes, permissionMode }), [allowedCommands, maxPatchBytes, permissionMode]);
  const [draft, setDraft] = useState(initial);
  const [saving, setSaving] = useState(false);
  useEffect(() => setDraft(initial), [initial]);
  const dirty = JSON.stringify(draft) !== JSON.stringify(initial);
  const save = async () => { if (!dirty || saving) return; setSaving(true); try { await onSave({ ...draft, allowedCommands: draft.allowedCommands.trim() }); } finally { setSaving(false); } };
  return <form className="grid gap-5" onSubmit={(event) => { event.preventDefault(); void save(); }}><FieldGroup><Field><FieldLabel htmlFor="actions-commands">允许命令（逗号分隔）</FieldLabel><Input id="actions-commands" className="font-mono" value={draft.allowedCommands} onChange={(event) => setDraft((current) => ({ ...current, allowedCommands: event.target.value }))} /></Field><Field><FieldLabel htmlFor="actions-patch">最大 Patch 字节数</FieldLabel><Input id="actions-patch" type="number" min={1024} max={5000000} value={draft.maxPatchBytes} onChange={(event) => setDraft((current) => ({ ...current, maxPatchBytes: Number(event.target.value) }))} /></Field><Field><FieldLabel>权限模式</FieldLabel><Select value={draft.permissionMode} onValueChange={(value) => setDraft((current) => ({ ...current, permissionMode: value ?? "trusted" }))}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="trusted">受信任</SelectItem><SelectItem value="safe">安全受限</SelectItem><SelectItem value="dangerous">完全放开</SelectItem></SelectContent></Select><FieldDescription>作用于 Actions gateway 的 exec_command 白名单与 apply_patch 大小限制。</FieldDescription></Field></FieldGroup><div className="flex justify-end"><Button type="submit" disabled={saving || !dirty}>{saving ? "保存中…" : "保存策略"}</Button></div></form>;
}

// src/lib/components/ActionsPolicyForm.svelte
<script lang="ts">
  import type { ActionsConfig } from "$lib/types";

  export interface ActionsPolicyDraft {
    allowedCommands: string;
    maxPatchBytes: number;
    permissionMode: string;
  }

  interface Props {
    allowedCommands: string;
    maxPatchBytes: number;
    permissionMode: string;
    onSave: (draft: ActionsPolicyDraft) => void | Promise<void>;
  }

  const PERMISSION_MODE_OPTIONS = [
    { value: "trusted", label: "受信任" },
    { value: "safe", label: "安全受限" },
    { value: "dangerous", label: "完全放开" },
  ] as const;

  let { allowedCommands, maxPatchBytes, permissionMode, onSave }: Props = $props();

  let draftCommands = $state("");
  let draftMaxPatch = $state(200_000);
  let draftMode = $state("trusted");
  let saving = $state(false);

  const dirty = $derived(
    draftCommands !== allowedCommands ||
      draftMaxPatch !== maxPatchBytes ||
      draftMode !== permissionMode,
  );

  $effect(() => {
    draftCommands = allowedCommands;
    draftMaxPatch = maxPatchBytes;
    draftMode = permissionMode;
  });

  async function save() {
    if (saving || !dirty) return;
    saving = true;
    try {
      await onSave({
        allowedCommands: draftCommands.trim(),
        maxPatchBytes: draftMaxPatch,
        permissionMode: draftMode,
      });
    } finally {
      saving = false;
    }
  }
</script>

<form
  class="grid gap-3"
  onsubmit={(event) => {
    event.preventDefault();
    void save();
  }}
>
  <label class="grid gap-1">
    <span class="text-xs text-[var(--text-muted)]">允许命令（逗号分隔）</span>
    <input
      type="text"
      class="rounded-md border border-[var(--border)] bg-[var(--page-bg)] px-2.5 py-1.5 font-mono text-sm"
      placeholder="pytest,python,cargo,npm,..."
      bind:value={draftCommands}
    />
  </label>
  <label class="grid gap-1">
    <span class="text-xs text-[var(--text-muted)]">最大 Patch 字节数</span>
    <input
      type="number"
      min="1024"
      max="5000000"
      class="rounded-md border border-[var(--border)] bg-[var(--page-bg)] px-2.5 py-1.5 text-sm"
      bind:value={draftMaxPatch}
    />
  </label>
  <label class="grid gap-1">
    <span class="text-xs text-[var(--text-muted)]">权限模式</span>
    <select
      class="rounded-md border border-[var(--border)] bg-[var(--page-bg)] px-2.5 py-1.5 text-sm"
      bind:value={draftMode}
    >
      {#each PERMISSION_MODE_OPTIONS as option}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
  </label>
  <p class="text-xs text-[var(--text-muted)]">
    作用于 Actions gateway 的 exec_command 白名单与 apply_patch 大小限制。
  </p>
  <div class="flex justify-end pt-1">
    <button
      type="submit"
      class="rounded-md bg-[var(--primary)] px-3 py-1.5 text-sm font-medium text-white transition-opacity hover:opacity-90 disabled:opacity-50"
      disabled={saving || !dirty}
    >
      {saving ? "保存中…" : "保存策略"}
    </button>
  </div>
</form>
