// src/components/admin/HealthPanel.tsx
import { useState } from "react";
import { Activity } from "lucide-react";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { runHealthChecks, type HealthItem } from "@/lib/api/health";

export function HealthPanel({ workspaceId }: { workspaceId: string }) {
  const [items, setItems] = useState<HealthItem[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  const run = async () => {
    if (busy || !workspaceId) return;
    setBusy(true); setError("");
    try { setItems(await runHealthChecks(workspaceId)); } catch (cause) { setError(String(cause)); setItems([]); } finally { setBusy(false); }
  };

  return <Card><CardHeader className="flex-row items-start justify-between gap-4"><div><CardTitle>健康检查</CardTitle><CardDescription className="mt-1">MCP、Actions 本地/公网 endpoint 与 OAuth 元数据</CardDescription></div><Button type="button" variant="outline" disabled={busy} onClick={() => void run()}><Activity data-icon="inline-start" />{busy ? "检查中…" : "运行健康检查"}</Button></CardHeader><CardContent className="grid gap-3">{error && <Alert variant="destructive"><AlertTitle>检查失败</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}{items.length > 0 ? items.map((item) => <div key={item.label} className="flex items-start justify-between gap-4 rounded-xl border p-3"><div><p className="text-sm font-medium">{item.label}</p><p className="mt-1 text-xs text-muted-foreground">{item.detail}</p>{!item.ok && item.hint && <p className="mt-1 text-xs text-primary">{item.hint}</p>}</div><Badge variant={item.ok ? "secondary" : "destructive"}>{item.ok ? "通过" : "失败"}</Badge></div>) : !busy && !error ? <p className="text-sm text-muted-foreground">尚未运行检查。</p> : null}</CardContent></Card>;
}

// src/lib/components/HealthPanel.svelte
<script lang="ts">
  import { runHealthChecks, type HealthItem } from "$lib/api/health";

  interface Props {
    workspaceId: string;
    onRunCheck?: (workspaceId: string) => Promise<HealthItem[]>;
  }

  let { workspaceId, onRunCheck }: Props = $props();

  let items = $state<HealthItem[]>([]);
  let busy = $state(false);
  let error = $state("");

  async function runCheck() {
    if (busy || !workspaceId) return;
    busy = true;
    error = "";
    try {
      items = onRunCheck ? await onRunCheck(workspaceId) : await runHealthChecks(workspaceId);
    } catch (err) {
      error = String(err);
      items = [];
    } finally {
      busy = false;
    }
  }
</script>

<section class="tx-card p-5">
  <div class="flex items-start justify-between gap-3">
    <div>
      <h3 class="font-semibold">健康检查</h3>
      <p class="mt-1 text-sm text-[var(--text-muted)]">
        MCP、Actions 本地/公网 endpoint 与 OAuth 元数据
      </p>
    </div>
    <button
      type="button"
      class="tx-btn-ghost shrink-0 disabled:opacity-50"
      disabled={busy}
      onclick={runCheck}
    >
      {busy ? "检查中…" : "运行健康检查"}
    </button>
  </div>

  {#if error}
    <p class="mt-4 rounded-lg border border-[var(--danger)]/30 bg-[var(--danger)]/10 px-3 py-2 text-sm text-[var(--danger)]">
      {error}
    </p>
  {/if}

  {#if items.length > 0}
    <ul class="mt-4 grid gap-2">
      {#each items as item (item.label)}
        <li
          class="flex items-start justify-between gap-3 rounded-lg bg-[var(--page-bg)] px-3 py-2"
        >
          <div class="min-w-0">
            <p class="text-sm font-medium">{item.label}</p>
            <p class="mt-0.5 text-xs text-[var(--text-muted)]">{item.detail}</p>
            {#if !item.ok && item.hint}
              <p class="mt-1 text-xs text-[var(--primary)]">{item.hint}</p>
            {/if}
          </div>
          <span
            class="shrink-0 rounded-sm px-2 py-0.5 text-xs font-medium"
            class:health-ok={item.ok}
            class:health-fail={!item.ok}
          >
            {item.ok ? "通过" : "失败"}
          </span>
        </li>
      {/each}
    </ul>
  {:else if !busy && !error}
    <p class="mt-4 text-sm text-[var(--text-muted)]">尚未运行检查。</p>
  {/if}
</section>

<style>
  .health-ok {
    background: color-mix(in oklch, var(--success) 15%, transparent);
    color: var(--success);
  }

  .health-fail {
    background: color-mix(in oklch, var(--danger) 15%, transparent);
    color: var(--danger);
  }
</style>
