// src/components/admin/RuntimePolicyForm.tsx
import { useEffect, useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export interface RuntimePolicyDraft {
  toolProfile: string;
  permissionMode: string;
  preferredShell: string;
  allowedCommands: string;
  workspaceLocalEntries: boolean;
  workspaceScriptExtensions: string;
  externalPaidCommandsEnabled: boolean;
  externalPaidMaxRunsPerDay: number;
  externalPaidMaxDurationSeconds: number;
}

function canonicalProfile(value: string) { return value === "advanced" || value === "read-only" ? value : "core"; }

export function RuntimePolicyForm(props: RuntimePolicyDraft & { onSave: (draft: RuntimePolicyDraft) => void | Promise<void> }) {
  const initial = useMemo<RuntimePolicyDraft>(() => ({
    toolProfile: canonicalProfile(props.toolProfile),
    permissionMode: props.permissionMode,
    preferredShell: props.preferredShell,
    allowedCommands: props.allowedCommands,
    workspaceLocalEntries: props.workspaceLocalEntries,
    workspaceScriptExtensions: props.workspaceScriptExtensions,
    externalPaidCommandsEnabled: props.externalPaidCommandsEnabled,
    externalPaidMaxRunsPerDay: props.externalPaidMaxRunsPerDay,
    externalPaidMaxDurationSeconds: props.externalPaidMaxDurationSeconds,
  }), [props.toolProfile, props.permissionMode, props.preferredShell, props.allowedCommands, props.workspaceLocalEntries, props.workspaceScriptExtensions, props.externalPaidCommandsEnabled, props.externalPaidMaxRunsPerDay, props.externalPaidMaxDurationSeconds]);
  const [draft, setDraft] = useState<RuntimePolicyDraft>(initial);
  const [saving, setSaving] = useState(false);
  useEffect(() => setDraft(initial), [initial]);
  const dirty = JSON.stringify(draft) !== JSON.stringify(initial);
  const update = <K extends keyof RuntimePolicyDraft>(key: K, value: RuntimePolicyDraft[K]) => setDraft((current) => ({ ...current, [key]: value }));

  const save = async () => {
    if (!dirty || saving) return;
    setSaving(true);
    try { await props.onSave({ ...draft, allowedCommands: draft.allowedCommands.trim(), workspaceScriptExtensions: draft.workspaceScriptExtensions.trim(), externalPaidMaxRunsPerDay: Math.max(1, Math.floor(draft.externalPaidMaxRunsPerDay)), externalPaidMaxDurationSeconds: Math.max(1, Math.floor(draft.externalPaidMaxDurationSeconds)) }); } finally { setSaving(false); }
  };

  return <form className="grid gap-5" onSubmit={(event) => { event.preventDefault(); void save(); }}><FieldGroup>
    <Field><FieldLabel>工具档位</FieldLabel><Select value={draft.toolProfile} onValueChange={(value) => update("toolProfile", value ?? "core")}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="core">核心工具</SelectItem><SelectItem value="advanced">完整工具</SelectItem><SelectItem value="read-only">只读工具</SelectItem></SelectContent></Select></Field>
    <Field><FieldLabel>Windows 默认 Shell</FieldLabel><Select value={draft.preferredShell} onValueChange={(value) => update("preferredShell", value ?? "auto")}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="auto">自动 / 直接执行</SelectItem><SelectItem value="pwsh">PowerShell 7 (pwsh)</SelectItem><SelectItem value="powershell">Windows PowerShell</SelectItem><SelectItem value="cmd">cmd.exe</SelectItem></SelectContent></Select><FieldDescription>仅在 exec_command 未显式指定 shell 时生效。</FieldDescription></Field>
    <div className="grid gap-4 rounded-xl border p-4"><label className="flex items-center gap-2 text-sm font-medium"><Checkbox checked={draft.externalPaidCommandsEnabled} onCheckedChange={(checked) => update("externalPaidCommandsEnabled", Boolean(checked))} />允许执行已识别的真实付费命令</label><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor="paid-runs">每日最大运行次数</FieldLabel><Input id="paid-runs" type="number" min={1} value={draft.externalPaidMaxRunsPerDay} onChange={(event) => update("externalPaidMaxRunsPerDay", Number(event.target.value))} /></Field><Field><FieldLabel htmlFor="paid-duration">单次最长秒数</FieldLabel><Input id="paid-duration" type="number" min={1} max={3600} value={draft.externalPaidMaxDurationSeconds} onChange={(event) => update("externalPaidMaxDurationSeconds", Number(event.target.value))} /></Field></div><p className="text-xs leading-5 text-muted-foreground">该权限只能由受信任控制面启用；项目仍可通过 .anchor/command-policy.yml 进一步收紧。</p></div>
    <Field><FieldLabel htmlFor="allowed-commands">系统命令（逗号分隔）</FieldLabel><Input id="allowed-commands" className="font-mono" value={draft.allowedCommands} onChange={(event) => update("allowedCommands", event.target.value)} /></Field>
    <label className="flex items-center gap-2 text-sm"><Checkbox checked={draft.workspaceLocalEntries} onCheckedChange={(checked) => update("workspaceLocalEntries", Boolean(checked))} />允许执行 Workspace 内本地入口</label>
    <Field><FieldLabel htmlFor="script-exts">本地脚本扩展名（逗号分隔）</FieldLabel><Input id="script-exts" className="font-mono" disabled={!draft.workspaceLocalEntries} value={draft.workspaceScriptExtensions} onChange={(event) => update("workspaceScriptExtensions", event.target.value)} /></Field>
    <Field><FieldLabel>权限模式</FieldLabel><Select value={draft.permissionMode} onValueChange={(value) => update("permissionMode", value ?? "trusted")}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="trusted">受信任</SelectItem><SelectItem value="safe">安全受限</SelectItem><SelectItem value="dangerous">完全放开</SelectItem></SelectContent></Select><FieldDescription>dangerous 只能由操作者在此控制面启用，模型参数不能作为用户批准凭证。</FieldDescription></Field>
  </FieldGroup><div className="flex justify-end"><Button type="submit" disabled={saving || !dirty}>{saving ? "保存中…" : "保存策略"}</Button></div></form>;
}

// src/lib/components/RuntimePolicyForm.svelte
<script lang="ts">
  export interface RuntimePolicyDraft {
    toolProfile: string;
    permissionMode: string;
    preferredShell: string;
    allowedCommands: string;
    workspaceLocalEntries: boolean;
    workspaceScriptExtensions: string;
    externalPaidCommandsEnabled: boolean;
    externalPaidMaxRunsPerDay: number;
    externalPaidMaxDurationSeconds: number;
  }

  interface Props {
    toolProfile: string;
    permissionMode: string;
    preferredShell: string;
    allowedCommands: string;
    workspaceLocalEntries: boolean;
    workspaceScriptExtensions: string;
    externalPaidCommandsEnabled: boolean;
    externalPaidMaxRunsPerDay: number;
    externalPaidMaxDurationSeconds: number;
    onSave: (draft: RuntimePolicyDraft) => void | Promise<void>;
  }

  const TOOL_PROFILE_OPTIONS = [
    { value: "core", label: "核心工具" },
    { value: "advanced", label: "完整工具" },
    { value: "read-only", label: "只读工具" },
  ] as const;

  const PERMISSION_MODE_OPTIONS = [
    { value: "trusted", label: "受信任" },
    { value: "safe", label: "安全受限" },
    { value: "dangerous", label: "完全放开" },
  ] as const;

  const PREFERRED_SHELL_OPTIONS = [
    { value: "auto", label: "自动 / 直接执行" },
    { value: "pwsh", label: "PowerShell 7 (pwsh)" },
    { value: "powershell", label: "Windows PowerShell" },
    { value: "cmd", label: "cmd.exe" },
  ] as const;

  let { toolProfile, permissionMode, preferredShell, allowedCommands, workspaceLocalEntries, workspaceScriptExtensions, externalPaidCommandsEnabled, externalPaidMaxRunsPerDay, externalPaidMaxDurationSeconds, onSave }: Props = $props();

  let draftProfile = $state("core");
  let draftMode = $state("trusted");
  let draftPreferredShell = $state("auto");
  let draftCommands = $state("");
  let draftLocalEntries = $state(true);
  let draftExtensions = $state(".exe,.bat,.cmd,.ps1");
  let draftExternalPaidEnabled = $state(false);
  let draftExternalPaidRuns = $state(1);
  let draftExternalPaidDuration = $state(1800);
  let saving = $state(false);

  function canonicalProfile(value: string) {
    if (value === "advanced" || value === "read-only") return value;
    return "core";
  }

  const dirty = $derived(
    draftProfile !== canonicalProfile(toolProfile) || draftMode !== permissionMode || draftPreferredShell !== preferredShell || draftCommands !== allowedCommands || draftLocalEntries !== workspaceLocalEntries || draftExtensions !== workspaceScriptExtensions || draftExternalPaidEnabled !== externalPaidCommandsEnabled || draftExternalPaidRuns !== externalPaidMaxRunsPerDay || draftExternalPaidDuration !== externalPaidMaxDurationSeconds,
  );

  $effect(() => {
    draftProfile = canonicalProfile(toolProfile);
    draftMode = permissionMode;
    draftPreferredShell = preferredShell;
    draftCommands = allowedCommands;
    draftLocalEntries = workspaceLocalEntries;
    draftExtensions = workspaceScriptExtensions;
    draftExternalPaidEnabled = externalPaidCommandsEnabled;
    draftExternalPaidRuns = externalPaidMaxRunsPerDay;
    draftExternalPaidDuration = externalPaidMaxDurationSeconds;
  });

  async function save() {
    if (saving || !dirty) return;
    saving = true;
    try {
      await onSave({ toolProfile: draftProfile, permissionMode: draftMode, preferredShell: draftPreferredShell, allowedCommands: draftCommands.trim(), workspaceLocalEntries: draftLocalEntries, workspaceScriptExtensions: draftExtensions.trim(), externalPaidCommandsEnabled: draftExternalPaidEnabled, externalPaidMaxRunsPerDay: Math.max(1, Math.floor(draftExternalPaidRuns)), externalPaidMaxDurationSeconds: Math.max(1, Math.floor(draftExternalPaidDuration)) });
    } finally {
      saving = false;
    }
  }
</script>

<form
  class="grid gap-3"
  onsubmit={(event) => {
    event.preventDefault();
    void save();
  }}
>
  <label class="grid gap-1">
    <span class="text-xs text-[var(--text-muted)]">工具档位</span>
    <select
      class="rounded-md border border-[var(--border)] bg-[var(--page-bg)] px-2.5 py-1.5 text-sm"
      bind:value={draftProfile}
    >
      {#each TOOL_PROFILE_OPTIONS as option}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
  </label>
  <label class="grid gap-1">
    <span class="text-xs text-[var(--text-muted)]">Windows 默认 Shell</span>
    <select class="rounded-md border border-[var(--border)] bg-[var(--page-bg)] px-2.5 py-1.5 text-sm" bind:value={draftPreferredShell}>
      {#each PREFERRED_SHELL_OPTIONS as option}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
    <span class="text-xs text-[var(--text-muted)]">仅在 exec_command 未显式指定 shell 时生效；显式 shell 始终优先。</span>
  </label>
  <fieldset class="grid gap-2 rounded-md border border-[var(--border)] p-3">
    <legend class="px-1 text-xs text-[var(--text-muted)]">真实付费命令</legend>
    <label class="flex items-center gap-2 text-sm">
      <input type="checkbox" bind:checked={draftExternalPaidEnabled} />
      <span>允许执行已识别的真实付费命令</span>
    </label>
    <div class="grid grid-cols-2 gap-2">
      <label class="grid gap-1">
        <span class="text-xs text-[var(--text-muted)]">每日最大运行次数</span>
        <input type="number" min="1" step="1" class="rounded-md border border-[var(--border)] bg-[var(--page-bg)] px-2.5 py-1.5 text-sm" bind:value={draftExternalPaidRuns} />
      </label>
      <label class="grid gap-1">
        <span class="text-xs text-[var(--text-muted)]">单次最长秒数</span>
        <input type="number" min="1" max="3600" class="rounded-md border border-[var(--border)] bg-[var(--page-bg)] px-2.5 py-1.5 text-sm" bind:value={draftExternalPaidDuration} />
      </label>
    </div>
    <p class="text-xs text-[var(--text-muted)]">每日次数不设额外的界面上限，保存时按正整数处理。此开关只能在受信任控制面保存；项目可在 .anchor/command-policy.yml 中进一步收紧命令匹配、次数和时长，模型参数不能启用该权限。</p>
  </fieldset>
  <label class="grid gap-1">
    <span class="text-xs text-[var(--text-muted)]">系统命令（逗号分隔）</span>
    <input type="text" class="rounded-md border border-[var(--border)] bg-[var(--page-bg)] px-2.5 py-1.5 font-mono text-sm" placeholder="python,git,curl,powershell,..." bind:value={draftCommands} />
  </label>
  <label class="flex items-center gap-2 text-sm">
    <input type="checkbox" bind:checked={draftLocalEntries} />
    <span>允许执行 Workspace 内本地入口</span>
  </label>
  <label class="grid gap-1">
    <span class="text-xs text-[var(--text-muted)]">本地脚本扩展名（逗号分隔）</span>
    <input type="text" class="rounded-md border border-[var(--border)] bg-[var(--page-bg)] px-2.5 py-1.5 font-mono text-sm" placeholder=".exe,.bat,.cmd,.ps1" bind:value={draftExtensions} disabled={!draftLocalEntries} />
  </label>
  <label class="grid gap-1">
    <span class="text-xs text-[var(--text-muted)]">权限模式</span>
    <select
      class="rounded-md border border-[var(--border)] bg-[var(--page-bg)] px-2.5 py-1.5 text-sm"
      bind:value={draftMode}
    >
      {#each PERMISSION_MODE_OPTIONS as option}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
  </label>
  <p class="text-xs text-[var(--text-muted)]">
    Workspace 本地入口按当前工作目录解析；系统命令与脚本类型均可按项目配置。dangerous 只能由操作者在此控制面启用，模型参数不能作为用户批准凭证。当前执行边界仍为 policy_only。
  </p>
  <div class="flex justify-end pt-1">
    <button
      type="submit"
      class="rounded-md bg-[var(--primary)] px-3 py-1.5 text-sm font-medium text-white disabled:opacity-50"
      disabled={saving || !dirty}
    >
      {saving ? "保存中…" : "保存策略"}
    </button>
  </div>
</form>
