// src/components/admin/SkillServiceConfigForm.tsx
import { useEffect, useMemo, useState } from "react";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field";
import { Textarea } from "@/components/ui/textarea";
import { inspectWorkspaceSkills } from "@/lib/api/workspaces";
import type { SkillInspection } from "@/lib/types";

const DEFAULT_ROOTS = ".agents/skills\n.codex/skills\nskills";
function normalizeRoots(value: string): string { const next = value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).join("\n"); return next || DEFAULT_ROOTS; }

export function SkillServiceConfigForm({ workspaceId, enabled, roots, onSave }: { workspaceId: string; enabled: boolean; roots: string; onSave: (config: { enabled: boolean; roots: string }) => void | Promise<void> }) {
  const initial = useMemo(() => ({ enabled, roots: normalizeRoots(roots) }), [enabled, roots]);
  const [draftEnabled, setDraftEnabled] = useState(enabled);
  const [draftRoots, setDraftRoots] = useState(initial.roots);
  const [saving, setSaving] = useState(false);
  const [scanning, setScanning] = useState(false);
  const [error, setError] = useState("");
  const [inspection, setInspection] = useState<SkillInspection | null>(null);
  useEffect(() => { setDraftEnabled(enabled); setDraftRoots(normalizeRoots(roots)); setInspection(null); setError(""); }, [enabled, roots]);
  const dirty = draftEnabled !== enabled || normalizeRoots(draftRoots) !== normalizeRoots(roots);
  const scan = async () => { if (scanning) return; setScanning(true); setError(""); try { setInspection(await inspectWorkspaceSkills(workspaceId, draftEnabled, normalizeRoots(draftRoots))); } catch (cause) { setError(String(cause)); } finally { setScanning(false); } };
  const save = async () => { if (!dirty || saving) return; setSaving(true); setError(""); try { const normalized = normalizeRoots(draftRoots); await onSave({ enabled: draftEnabled, roots: normalized }); setDraftRoots(normalized); } catch (cause) { setError(String(cause)); } finally { setSaving(false); } };
  return <form className="grid gap-4" onSubmit={(event) => { event.preventDefault(); void save(); }}><div className="flex items-start justify-between gap-4 rounded-xl border p-4"><div><p className="text-sm font-medium">通过 MCP 提供 Agent Skills</p><p className="mt-1 text-xs leading-5 text-muted-foreground">客户端可调用 list_skills、load_skill、read_skill_resource，并读取 skill://index.json。</p></div><label className="flex shrink-0 items-center gap-2 text-xs text-muted-foreground"><Checkbox checked={draftEnabled} onCheckedChange={(checked) => setDraftEnabled(Boolean(checked))} />{draftEnabled ? "已启用" : "已关闭"}</label></div><Field><FieldLabel htmlFor="skill-roots">Skill 根目录（每行一个）</FieldLabel><Textarea id="skill-roots" className="min-h-32 font-mono text-xs" disabled={!draftEnabled} value={draftRoots} onChange={(event) => setDraftRoots(event.target.value)} /><FieldDescription>相对路径以当前 workspace 为基准，支持 ~/；每个 Skill 必须包含合法 SKILL.md。</FieldDescription></Field>{error && <Alert variant="destructive"><AlertTitle>Skill 配置错误</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}{inspection && <Card><CardContent className="grid gap-3 p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium">{inspection.enabled ? `发现 ${inspection.skills.length} 个 Skill` : "Skill 服务已关闭"}</p><Badge variant="outline">脚本策略 · {inspection.scriptExecutionPolicy}</Badge></div>{inspection.skills.map((skill) => <div key={`${skill.sourceId}/${skill.relativePath}`} className="rounded-lg border p-3"><div className="flex justify-between gap-3"><code className="text-xs font-semibold">{skill.name}</code><span className="text-[11px] text-muted-foreground">{skill.resources.length} resources · {skill.scripts.length} scripts</span></div><p className="mt-1 text-xs text-muted-foreground">{skill.description}</p><p className="mt-1 truncate font-mono text-[10px] text-muted-foreground">{skill.uri}</p></div>)}{inspection.warnings.map((warning) => <p key={warning} className="text-xs text-amber-600">{warning}</p>)}<p className="border-t pt-2 font-mono text-[10px] text-muted-foreground">snapshot={inspection.snapshotMode} · catalog={inspection.catalogDigest.slice(0, 26)}…</p></CardContent></Card>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={scanning} onClick={() => void scan()}>{scanning ? "扫描中…" : "扫描目录"}</Button><Button type="submit" disabled={saving || !dirty}>{saving ? "保存中…" : "保存 Skill 服务"}</Button></div></form>;
}

// src/lib/components/SkillServiceConfigForm.svelte
<script lang="ts">
  import { inspectWorkspaceSkills } from "$lib/api/workspaces";
  import type { SkillInspection } from "$lib/types";

  const DEFAULT_ROOTS = ".agents/skills\n.codex/skills\nskills";

  interface SkillServiceConfig {
    enabled: boolean;
    roots: string;
  }

  interface Props {
    workspaceId: string;
    enabled: boolean;
    roots: string;
    onSave: (config: SkillServiceConfig) => void | Promise<void>;
  }

  let { workspaceId, enabled, roots, onSave }: Props = $props();
  let draftEnabled = $state(true);
  let draftRoots = $state("");
  let saving = $state(false);
  let scanning = $state(false);
  let error = $state("");
  let inspection = $state<SkillInspection | null>(null);

  const dirty = $derived(draftEnabled !== enabled || normalizeRoots(draftRoots) !== normalizeRoots(roots));

  $effect(() => {
    draftEnabled = enabled;
    draftRoots = roots;
    inspection = null;
    error = "";
  });

  function normalizeRoots(value: string): string {
    const normalized = value
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean)
      .join("\n");
    return normalized || DEFAULT_ROOTS;
  }

  async function scan() {
    if (scanning) return;
    scanning = true;
    error = "";
    try {
      inspection = await inspectWorkspaceSkills(
        workspaceId,
        draftEnabled,
        normalizeRoots(draftRoots),
      );
    } catch (cause) {
      error = cause instanceof Error ? cause.message : String(cause);
    } finally {
      scanning = false;
    }
  }

  async function save() {
    if (saving || !dirty) return;
    saving = true;
    error = "";
    try {
      const normalized = normalizeRoots(draftRoots);
      await onSave({ enabled: draftEnabled, roots: normalized });
      draftRoots = normalized;
    } catch (cause) {
      error = cause instanceof Error ? cause.message : String(cause);
    } finally {
      saving = false;
    }
  }
</script>

<form
  class="grid gap-4"
  onsubmit={(event) => {
    event.preventDefault();
    void save();
  }}
>
  <div class="flex items-start justify-between gap-5 rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)] px-4 py-3">
    <div class="min-w-0">
      <p class="text-sm font-medium text-[var(--color-text-primary)]">通过 MCP 提供 Agent Skills</p>
      <p class="mt-1 text-xs leading-5 text-[var(--color-text-muted)]">
        客户端可调用 <code class="font-mono">list_skills</code>、<code class="font-mono">load_skill</code>
        和 <code class="font-mono">read_skill_resource</code>，也可读取
        <code class="font-mono">skill://index.json</code>。
      </p>
    </div>
    <label class="inline-flex shrink-0 items-center gap-2 text-xs text-[var(--color-text-secondary)]">
      <input type="checkbox" bind:checked={draftEnabled} />
      {draftEnabled ? "已启用" : "已关闭"}
    </label>
  </div>

  <label class="grid gap-1.5">
    <span class="text-xs text-[var(--color-text-muted)]">Skill 根目录（每行一个）</span>
    <textarea
      class="min-h-32 resize-y rounded-md border border-[var(--color-border)] bg-[var(--color-bg)] px-3 py-2 font-mono text-xs leading-5 disabled:opacity-50"
      placeholder={".agents/skills\n.codex/skills\nskills\n~/.codex/skills"}
      spellcheck="false"
      disabled={!draftEnabled}
      bind:value={draftRoots}
    ></textarea>
  </label>

  <p class="text-xs leading-5 text-[var(--color-text-muted)]">
    相对路径以当前 workspace 为基准，支持 <code class="font-mono">~/</code>。根目录可以直接是一个
    Skill，也可以包含两层以内的 Skill 子目录；每个 Skill 必须包含合法的
    <code class="font-mono">SKILL.md</code>。没有专用脚本执行器；通过
    <code class="font-mono">exec_command</code> 引用 Skill 脚本时必须显式确认，且脚本摘要必须与目录快照一致。
  </p>

  {#if error}
    <p class="text-xs text-[var(--color-danger)]">{error}</p>
  {/if}

  {#if inspection}
    <div class="grid gap-3 rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)] p-3">
      <div class="flex flex-wrap items-center justify-between gap-2">
        <p class="text-sm font-medium text-[var(--color-text-primary)]">
          {inspection.enabled ? `发现 ${inspection.skills.length} 个 Skill` : "Skill 服务已关闭"}
        </p>
        <span class="text-xs text-[var(--color-text-muted)]">
          脚本策略：{inspection.scriptExecutionPolicy}
        </span>
      </div>

      {#if inspection.skills.length}
        <div class="grid max-h-64 gap-2 overflow-y-auto pr-1">
          {#each inspection.skills as skill}
            <div class="rounded-md border border-[var(--color-border)] px-3 py-2.5">
              <div class="flex flex-wrap items-baseline justify-between gap-2">
                <code class="font-mono text-xs font-semibold text-[var(--color-text-primary)]">{skill.name}</code>
                <span class="text-[11px] text-[var(--color-text-muted)]">
                  {skill.resources.length} resources · {skill.scripts.length} scripts
                </span>
              </div>
              <p class="mt-1 text-xs leading-5 text-[var(--color-text-secondary)]">{skill.description}</p>
              <p class="mt-1 text-[11px] text-[var(--color-text-muted)]">
                来源：{skill.sourceId}/{skill.relativePath} · 包摘要：{skill.digest.slice(0, 22)}…
              </p>
              <p class="mt-1 truncate font-mono text-[10px] text-[var(--color-text-muted)]">{skill.uri}</p>
              {#if skill.resourceTruncated}
                <p class="mt-1 text-xs text-[var(--color-warning)]">资源清单已达到单 Skill 上限。</p>
              {/if}
            </div>
          {/each}
        </div>
      {/if}
      <p class="border-t border-[var(--color-border)] pt-2 font-mono text-[10px] text-[var(--color-text-muted)]">
        snapshot={inspection.snapshotMode} · catalog={inspection.catalogDigest.slice(0, 26)}…
      </p>

      {#if inspection.warnings.length}
        <div class="grid gap-1 border-t border-[var(--color-border)] pt-2">
          {#each inspection.warnings as warning}
            <p class="text-xs leading-5 text-[var(--color-warning)]">{warning}</p>
          {/each}
        </div>
      {/if}
    </div>
  {/if}

  <div class="flex flex-wrap justify-end gap-2 pt-1">
    <button
      type="button"
      class="tx-btn-ghost px-3 py-1.5 text-sm disabled:opacity-50"
      disabled={scanning}
      onclick={() => void scan()}
    >
      {scanning ? "扫描中…" : "扫描目录"}
    </button>
    <button
      type="submit"
      class="tx-btn-primary px-3 py-1.5 text-sm disabled:opacity-50"
      disabled={saving || !dirty}
    >
      {saving ? "保存中…" : "保存 Skill 服务"}
    </button>
  </div>
</form>
