// src/components/admin/WorkspaceMetaForm.tsx
import { FolderInput, FolderOpen } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Field, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { openWorkspaceDirectory } from "@/lib/api/workspaces";
import { open } from "@/lib/platform/dialog";

export function WorkspaceMetaForm({ name, path, onSave, onUpdatePath }: { name: string; path: string; onSave: (name: string) => void | Promise<void>; onUpdatePath: (path: string) => void | Promise<void> }) {
  const [draftName, setDraftName] = useState(name);
  const [saving, setSaving] = useState(false);
  const [opening, setOpening] = useState(false);
  const [updatingPath, setUpdatingPath] = useState(false);

  useEffect(() => setDraftName(name), [name]);
  const dirty = draftName.trim().length > 0 && draftName.trim() !== name;

  const save = async () => {
    if (!dirty || saving) return;
    setSaving(true);
    try { await onSave(draftName.trim()); } finally { setSaving(false); }
  };

  const openDirectory = async () => {
    setOpening(true);
    try { await openWorkspaceDirectory(path); } catch (error) { toast.error("无法打开目录", { description: String(error) }); } finally { setOpening(false); }
  };

  const updateDirectory = async () => {
    setUpdatingPath(true);
    try {
      const selected = await open({ directory: true, multiple: false, defaultPath: path || undefined });
      if (!selected || Array.isArray(selected)) return;
      const next = selected.trim().replace(/[\\/]+$/, "");
      const current = path.trim().replace(/[\\/]+$/, "");
      if (next && next !== current) await onUpdatePath(next);
    } catch (error) {
      toast.error("无法更新目录", { description: String(error) });
    } finally {
      setUpdatingPath(false);
    }
  };

  return (
    <form className="grid gap-3 xl:grid-cols-[minmax(12rem,0.7fr)_minmax(20rem,1.3fr)_auto] xl:items-end" onSubmit={(event) => { event.preventDefault(); void save(); }}>
      <Field><FieldLabel htmlFor="workspace-name">工作区名称</FieldLabel><Input id="workspace-name" value={draftName} onChange={(event) => setDraftName(event.target.value)} /></Field>
      <Field>
        <FieldLabel>路径</FieldLabel>
        <div className="flex min-w-0 gap-2">
          <Input readOnly title={path} value={path} className="min-w-0 flex-1 font-mono text-xs" />
          <Button type="button" variant="outline" disabled={opening || !path} onClick={() => void openDirectory()}><FolderOpen data-icon="inline-start" />{opening ? "打开中…" : "打开目录"}</Button>
          <Button type="button" variant="outline" disabled={updatingPath} onClick={() => void updateDirectory()}><FolderInput data-icon="inline-start" />{updatingPath ? "选择中…" : "更新目录"}</Button>
        </div>
      </Field>
      <Button type="submit" disabled={!dirty || saving}>{saving ? "保存中…" : "保存名称"}</Button>
    </form>
  );
}

// src/lib/components/WorkspaceMetaForm.svelte
<script lang="ts">
  import { FolderInput, FolderOpen } from "@lucide/svelte";
  import { open } from "$lib/platform/dialog";
  import { openWorkspaceDirectory } from "$lib/api/workspaces";
  import { showToast } from "$lib/stores/toast";

  interface Props {
    name: string;
    path: string;
    onSave: (name: string) => void | Promise<void>;
    onUpdatePath: (path: string) => void | Promise<void>;
  }

  let { name, path, onSave, onUpdatePath }: Props = $props();

  let draftName = $state("");
  let saving = $state(false);
  let opening = $state(false);
  let updatingPath = $state(false);

  const dirty = $derived(draftName.trim() !== name && draftName.trim().length > 0);

  $effect(() => {
    draftName = name;
  });

  async function save() {
    if (saving || !dirty) return;
    saving = true;
    try {
      await onSave(draftName.trim());
    } finally {
      saving = false;
    }
  }

  async function openDirectory() {
    if (opening || !path.trim()) return;
    opening = true;
    try {
      await openWorkspaceDirectory(path);
    } catch (error) {
      showToast(String(error), {
        kind: "error",
        title: "无法打开目录",
      });
    } finally {
      opening = false;
    }
  }

  function normalizePath(value: string): string {
    return value.trim().replace(/[\\/]+$/, "");
  }

  async function updateDirectory() {
    if (updatingPath) return;
    updatingPath = true;
    try {
      const selected = await open({
        directory: true,
        multiple: false,
        defaultPath: path.trim() || undefined,
      });
      if (!selected || Array.isArray(selected)) return;
      const nextPath = normalizePath(selected);
      if (!nextPath || nextPath === normalizePath(path)) return;
      await onUpdatePath(nextPath);
    } catch (error) {
      showToast(String(error), {
        kind: "error",
        title: "无法更新目录",
      });
    } finally {
      updatingPath = false;
    }
  }
</script>

<form
  class="flex flex-col gap-3 sm:flex-row sm:items-end"
  onsubmit={(event) => {
    event.preventDefault();
    void save();
  }}
>
  <label class="tx-field min-w-0 flex-1">
    <span class="tx-label">工作区名称</span>
    <input type="text" class="tx-input" bind:value={draftName} />
  </label>
  <div class="tx-field min-w-0 flex-1">
    <span class="tx-label">路径</span>
    <div class="flex min-w-0 items-center gap-2">
      <p
        class="tx-mono min-w-0 flex-1 truncate rounded-[10px] border border-transparent px-2.5 py-2 text-[var(--text-secondary)]"
        title={path}
      >
        {path}
      </p>
      <button
        type="button"
        class="tx-btn-ghost shrink-0 px-2.5 py-1.5 text-xs"
        disabled={opening || !path.trim()}
        onclick={() => void openDirectory()}
      >
        <FolderOpen size={14} class="inline-block" />
        <span class="ml-1">{opening ? "打开中…" : "打开目录"}</span>
      </button>
      <button
        type="button"
        class="tx-btn-ghost shrink-0 px-2.5 py-1.5 text-xs"
        disabled={updatingPath}
        onclick={() => void updateDirectory()}
      >
        <FolderInput size={14} class="inline-block" />
        <span class="ml-1">{updatingPath ? "选择中…" : "更新目录"}</span>
      </button>
    </div>
  </div>
  <button type="submit" class="tx-btn-primary shrink-0" disabled={saving || !dirty}>
    {saving ? "保存中…" : "保存名称"}
  </button>
</form>
